### ISSUE TITLE
do you have to specify the reducer here? 

### ISSUE THREAD

**Issue by DiogenisPanagiotis** [RADesai/merrn-sample#1]
can you just get the entire state like below?

_const { status, models } = state;_

https://github.com/RADesai/merrn-sample/blob/15e5a5d3927636834357c975252e64b496daf0a3/src/containers/App.js#L28

**Comment by RADesai** [comment]
Since we are using a rootReducer which combines all reducers, we'll have to access that portion of the application state as we do in the current implementation, which is to go through the rootReducer and specifically mention that we are pulling state from the appReducer.

**Comment by RADesai** [comment]
Closing this issue for now, please have a look at the container once again as it is now pulling state data from multiple reducers. Please open another issue if you have any other concerns!
